apiVersion: 1

datasources:
  - name: Homely Postgres
    uid: homely-pg
    type: postgres
    access: proxy
    url: db:5432
    user: grafana_reader
    isDefault: true
    jsonData:
      database: $POSTGRES_DB
      sslmode: disable
      maxOpenConns: 4
    secureJsonData:
      password: $GRAFANA_DB_PASSWORD
